#############################################################################
# Generated by PAGE version 4.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""




#############################################################################
## vTcl Code to Load Stock Images


if {![info exist vTcl(sourcing)]} {
#############################################################################
## Procedure:  vTcl:rename

proc ::vTcl:rename {name} {
    ## This procedure may be used free of restrictions.
    ##    Exception added by Christian Gavin on 08/08/02.
    ## Other packages and widget toolkits have different licensing requirements.
    ##    Please read their license agreements for details.
    regsub -all "\\." $name "_" ret
    regsub -all "\\-" $ret "_" ret
    regsub -all " " $ret "_" ret
    regsub -all "/" $ret "__" ret
    regsub -all "::" $ret "__" ret

    return [string tolower $ret]
}

#############################################################################
## Procedure:  vTcl:image:create_new_image

proc ::vTcl:image:create_new_image {filename {description {no description}} {type {}} {data {}}} {
    ## This procedure may be used free of restrictions.
    ##    Exception added by Christian Gavin on 08/08/02.
    ## Other packages and widget toolkits have different licensing requirements.
    ##    Please read their license agreements for details.
    # Does the image already exist?
    if {[info exists ::vTcl(images,files)]} {
        if {[lsearch -exact $::vTcl(images,files) $filename] > -1} { return }
    }
    if {![info exists ::vTcl(sourcing)] && [string length $data] > 0} {
        set object [image create  [vTcl:image:get_creation_type $filename]  -data $data]
    } else {
        # Wait a minute... Does the file actually exist?
        if {! [file exists $filename] } {
            # Try current directory
            set script [file dirname [info script]]
            set filename [file join $script [file tail $filename] ]
        }

        if {![file exists $filename]} {
            set description "file not found!"
            ## will add 'broken image' again when img is fixed, for
            ## now create empty
            set object [image create photo -width 1 -height 1]
        } else {
            set object [image create  [vTcl:image:get_creation_type $filename]  -file $filename]
        }
    }

    set reference [vTcl:rename $filename]
    set ::vTcl(images,$reference,image)       $object
    set ::vTcl(images,$reference,description) $description
    set ::vTcl(images,$reference,type)        $type
    set ::vTcl(images,filename,$object)       $filename

    lappend ::vTcl(images,files) $filename
    lappend ::vTcl(images,$type) $object
    set ::vTcl(imagefile,$object) $filename   ;# Rozen
    # return image name in case caller might want it
    return $object
}

#############################################################################
## Procedure:  vTcl:image:get_image

proc ::vTcl:image:get_image {filename} {
    ## This procedure may be used free of restrictions.
    ##    Exception added by Christian Gavin on 08/08/02.
    ## Other packages and widget toolkits have different licensing requirements.
    ##    Please read their license agreements for details.

    set reference [vTcl:rename $filename]

    # Let's do some checking first
    if {![info exists ::vTcl(images,$reference,image)]} {
        # Well, the path may be wrong; in that case check
        # only the filename instead, without the path.

        set imageTail [file tail $filename]

        foreach oneFile $::vTcl(images,files) {
            if {[file tail $oneFile] == $imageTail} {
                set reference [vTcl:rename $oneFile]
                break
            }
        }
    }
    # Rozen. There follows a hack in case one wants to rerun a tcl
    # file which contains a file name where an image is expected.
    if {![info exists ::vTcl(images,$reference,image)]} {
        set ::vTcl(images,$reference,image)  [vTcl:image:create_new_image $filename]
    }
    return $::vTcl(images,$reference,image)
}

#############################################################################
## Procedure:  vTcl:image:get_creation_type

proc ::vTcl:image:get_creation_type {filename} {
    ## This procedure may be used free of restrictions.
    ##    Exception added by Christian Gavin on 08/08/02.
    ## Other packages and widget toolkits have different licensing requirements.
    ##    Please read their license agreements for details.

    switch [string tolower [file extension $filename]] {
        .ppm -
        .jpg -
        .bmp -
        .gif    {return photo}
        .xbm    {return bitmap}
        default {return photo}
    }
}

foreach img {


            } {
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

}
#############################################################################
## vTcl Code to Load User Images

catch {package require Img}

foreach img {

        {{$[pwd]/logo_wishful.png} {user image} user {}}
        {{$[pwd]/logo_cnit2.png} {user image} user {}}
        {{$[pwd]/topology_final.png} {user image} user {}}

            } {
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) wheat
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #b2c9f4
set vTcl(analog_color_p) #eaf4b2
set vTcl(analog_color_m) #f4bcb2
set vTcl(active_fg) #111111
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 22 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top34
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.m37
    set site_3_0 $base.m37
    set site_3_0 $base.tFr39
    set site_5_0 .top34.tFr39.tNo40.t0 
    set site_5_0 $site_5_0
    set site_6_0 $site_5_0.lab41
    set site_6_0 $site_5_0.lab37
    set site_6_0 $site_5_0.lab38
    set site_5_1 .top34.tFr39.tNo40.pg0 
    set site_5_0 $site_5_1
    set site_5_2 .top34.tFr39.tNo40.pg1 
    set site_5_3 .top34.tFr39.tNo40.t1 
    set site_5_0 $site_5_3
    set site_6_0 $site_5_0.lab37
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top34 {base} {
    if {$base == ""} {
        set base .top34
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m37" -background {#ffffff} -highlightbackground wheat \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1448x924+94+29
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1170
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Demo LORA Traffic Generator"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    menu $top.m37 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background wheat -font TkMenuFont -foreground {#000000} -tearoff 0 
    $top.m37 add cascade \
        -menu "$top.m37.men38" -activebackground {#d8d8d8} \
        -activeforeground {#111111} -background wheat -font TkMenuFont \
        -foreground {#000000} -label File 
    set site_3_0 $top.m37
    menu $site_3_0.men38 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    $site_3_0.men38 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background wheat -command {#Save} -font TkMenuFont \
        -foreground {#000000} -label Save 
    $site_3_0.men38 add separator \
        -background wheat 
    $site_3_0.men38 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background wheat -command {#Quit} -font TkMenuFont \
        -foreground {#000000} -label Quit 
    $top.m37 add cascade \
        -menu "$top.m37.men40" -activebackground {#d8d8d8} \
        -activeforeground {#111111} -background wheat -font TkMenuFont \
        -foreground {#000000} -label Edit 
    set site_3_0 $top.m37
    menu $site_3_0.men40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    ttk::style configure TFrame -background #d9d9d9
    ttk::frame $top.tFr39 \
        -borderwidth 2 -relief groove -width 1435 -height 830 
    vTcl:DefineAlias "$top.tFr39" "TFrame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr39
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $site_3_0.tNo40
    frame $site_3_0.tNo40.t0 \
        -relief groove -background {#d9d9d9} -height 556 \
        -highlightbackground wheat -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo40.t0" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $site_3_0.tNo40 add .top34.tFr39.tNo40.t0 \
        -padding 0 -sticky nsew -state normal -text {Error Detection} \
        -image {} -compound none -underline -1 
    set site_5_0  $site_3_0.tNo40.t0
    labelframe $site_5_0.lab41 \
        -foreground black -text Topology -background {#d9d9d9} -height 325 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 500 
    vTcl:DefineAlias "$site_5_0.lab41" "LabelframeTopology" vTcl:WidgetProc "Toplevel1" 1
    set site_6_0 $site_5_0.lab41
    label $site_6_0.lab38 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black \
        -image [vTcl:image:get_image [file join D:/ ownCloud wishful-framework-cnit wishful-github-manifest-7 final_showcase showcase_GUI cnit_GUI topology_final.png]] 
    vTcl:DefineAlias "$site_6_0.lab38" "LabelTopologyImage" vTcl:WidgetProc "Toplevel1" 1
    place $site_6_0.lab38 \
        -in $site_6_0 -x 8 -y 18 -width 464 -relwidth 0 -height 271 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_5_0.lab42 \
        -foreground black -text {Channel Time} -background {#d9d9d9} \
        -height 250 -highlightbackground {#d9d9d9} -highlightcolor black \
        -width 1360 
    vTcl:DefineAlias "$site_5_0.lab42" "LabelframeMonitor" vTcl:WidgetProc "Toplevel1" 1
    labelframe $site_5_0.cpd38 \
        -foreground black -text {Technology Detection} -background {#d9d9d9} \
        -height 325 -highlightbackground {#d9d9d9} -highlightcolor black \
        -width 620 
    vTcl:DefineAlias "$site_5_0.cpd38" "LabelframeDetection1" vTcl:WidgetProc "Toplevel1" 1
    labelframe $site_5_0.lab37 \
        -foreground black -text Controller -background {#d9d9d9} -height 325 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 220 
    vTcl:DefineAlias "$site_5_0.lab37" "LabelframeController" vTcl:WidgetProc "Toplevel1" 1
    set site_6_0 $site_5_0.lab37
    radiobutton $site_6_0.rad38 \
        -activebackground {#f4bcb2} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -indicatoron 0 -justify left -text On -value 1 \
        -variable wifiActivation 
    vTcl:DefineAlias "$site_6_0.rad38" "RadiobuttonRadiobuttonWifiOn" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_6_0.cpd39 \
        -activebackground {#f4bcb2} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -indicatoron 0 -justify left -text Off -value 0 \
        -variable wifiActivation 
    vTcl:DefineAlias "$site_6_0.cpd39" "RadiobuttonWifiOff" vTcl:WidgetProc "Toplevel1" 1
    label $site_6_0.lab40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text WiFi 
    vTcl:DefineAlias "$site_6_0.lab40" "LabelWiFi" vTcl:WidgetProc "Toplevel1" 1
    label $site_6_0.cpd43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text LTE 
    vTcl:DefineAlias "$site_6_0.cpd43" "LabelLte" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_6_0.cpd47 \
        -activebackground {#f4bcb2} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -indicatoron 0 -justify left -text Off -value 0 \
        -variable lteActivation 
    vTcl:DefineAlias "$site_6_0.cpd47" "RadiobuttonLteOff" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_6_0.cpd49 \
        -activebackground {#f4bcb2} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -indicatoron 0 -justify left -text On -value 1 \
        -variable lteActivation 
    vTcl:DefineAlias "$site_6_0.cpd49" "RadiobuttonLteOn" vTcl:WidgetProc "Toplevel1" 1
    label $site_6_0.lab37 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text TDMA 
    vTcl:DefineAlias "$site_6_0.lab37" "Label3" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_6_0.rad39 \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -indicatoron 0 -justify left -text Off -value 0 \
        -variable tdmaActivation 
    vTcl:DefineAlias "$site_6_0.rad39" "RadiobuttonTdmaOff" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_6_0.cpd41 \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -indicatoron 0 -justify left -text On -value 1 \
        -variable tdmaActivation 
    vTcl:DefineAlias "$site_6_0.cpd41" "RadiobuttonTdmaOn" vTcl:WidgetProc "Toplevel1" 1
    place $site_6_0.rad38 \
        -in $site_6_0 -x 151 -y 30 -width 56 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.cpd39 \
        -in $site_6_0 -x 86 -y 30 -width 58 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_6_0.lab40 \
        -in $site_6_0 -x 30 -y 30 -anchor nw -bordermode ignore 
    place $site_6_0.cpd43 \
        -in $site_6_0 -x 30 -y 90 -width 29 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_6_0.cpd47 \
        -in $site_6_0 -x 85 -y 92 -width 58 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_6_0.cpd49 \
        -in $site_6_0 -x 150 -y 92 -width 56 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_6_0.lab37 \
        -in $site_6_0 -x 30 -y 150 -anchor nw -bordermode ignore 
    place $site_6_0.rad39 \
        -in $site_6_0 -x 84 -y 146 -width 58 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.cpd41 \
        -in $site_6_0 -x 150 -y 146 -width 58 -height 25 -anchor nw \
        -bordermode ignore 
    labelframe $site_5_0.lab38 \
        -foreground black -text {Solution Global Controller LOG} \
        -background {#d9d9d9} -height 175 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 1360 
    vTcl:DefineAlias "$site_5_0.lab38" "LabelframeLog" vTcl:WidgetProc "Toplevel1" 1
    set site_6_0 $site_5_0.lab38
    listbox $site_6_0.lis40 \
        -background white -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -height 142 -highlightbackground {#d9d9d9} \
        -highlightcolor black -selectbackground {#c4c4c4} \
        -selectforeground black -width 1324 
    .top34.tFr39.tNo40.t0.lab38.lis40 configure -font font10
    .top34.tFr39.tNo40.t0.lab38.lis40 insert end text
    vTcl:DefineAlias "$site_6_0.lis40" "ListboxLog" vTcl:WidgetProc "Toplevel1" 1
    place $site_6_0.lis40 \
        -in $site_6_0 -x 10 -y 20 -width 1324 -relwidth 0 -height 142 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab41 \
        -in $site_5_0 -x 30 -y 10 -width 500 -relwidth 0 -height 325 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab42 \
        -in $site_5_0 -x 30 -y 480 -rely 0.052 -width 1360 -relwidth 0 \
        -height 250 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.cpd38 \
        -in $site_5_0 -x 770 -y 10 -width 620 -relwidth 0 -height 325 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab37 \
        -in $site_5_0 -x 540 -y 10 -width 220 -relwidth 0 -height 325 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab38 \
        -in $site_5_0 -x 30 -y 340 -width 1360 -relwidth 0 -height 175 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.tNo40.pg0 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo40.pg0" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
    $site_3_0.tNo40 add .top34.tFr39.tNo40.pg0 \
        -padding 0 -sticky nsew -state normal -text {Spectral Scan} -image {} \
        -compound none -underline -1 
    set site_5_1  $site_3_0.tNo40.pg0
    labelframe $site_5_1.lab37 \
        -foreground black -text Spectral -background {#d9d9d9} -height 645 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 1380 
    vTcl:DefineAlias "$site_5_1.lab37" "LabelframeWaterFall" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_1.lab37 \
        -in $site_5_1 -x 10 -y 10 -width 1380 -relwidth 0 -height 645 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.tNo40.pg1 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo40.pg1" "TNotebook1_t3" vTcl:WidgetProc "Toplevel1" 1
    $site_3_0.tNo40 add .top34.tFr39.tNo40.pg1 \
        -padding 0 -sticky nsew -state normal -text {USRP Conf} -image {} \
        -compound none -underline -1 
    set site_5_2  $site_3_0.tNo40.pg1
    frame $site_3_0.tNo40.t1 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo40.t1" "TNotebook1_t4" vTcl:WidgetProc "Toplevel1" 1
    $site_3_0.tNo40 add .top34.tFr39.tNo40.t1 \
        -padding 0 -sticky nsew -state normal -text {Gateway Conf} -image {} \
        -compound none -underline -1 
    set site_5_3  $site_3_0.tNo40.t1
    labelframe $site_5_3.lab37 \
        -foreground black -text {Gateway Conf} -background {#d9d9d9} \
        -height 315 -highlightbackground {#d9d9d9} -highlightcolor black \
        -width 920 
    vTcl:DefineAlias "$site_5_3.lab37" "GatewayConfFrame" vTcl:WidgetProc "Toplevel1" 1
    set site_6_0 $site_5_3.lab37
    button $site_6_0.but38 \
        -activebackground {#f4bcb2} -activeforeground black \
        -background {#d9d9d9} -command OpenFileDialog \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Select... 
    vTcl:DefineAlias "$site_6_0.but38" "FileDialogButton" vTcl:WidgetProc "Toplevel1" 1
    label $site_6_0.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Select Gateway File} 
    vTcl:DefineAlias "$site_6_0.lab39" "SelectGatewayFileLabel" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but41 \
        -activebackground {#f4bcb2} -activeforeground black \
        -background {#d9d9d9} -command StartGatewayCommand \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Start Gateway} 
    vTcl:DefineAlias "$site_6_0.but41" "StartGatewayButton" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but42 \
        -activebackground {#f4bcb2} -activeforeground black \
        -background {#d9d9d9} -command StopGatewayCommand \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Stop Gateway} 
    vTcl:DefineAlias "$site_6_0.but42" "StopGatewayButton" vTcl:WidgetProc "Toplevel1" 1
    entry $site_6_0.ent43 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_6_0.ent43" "GatewayFilePathEntry" vTcl:WidgetProc "Toplevel1" 1
    place $site_6_0.but38 \
        -in $site_6_0 -x 550 -y 50 -anchor nw -bordermode ignore 
    place $site_6_0.lab39 \
        -in $site_6_0 -x 30 -y 50 -width 124 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.but41 \
        -in $site_6_0 -x 40 -y 90 -width 167 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.but42 \
        -in $site_6_0 -x 240 -y 90 -width 167 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.ent43 \
        -in $site_6_0 -x 160 -y 50 -width 374 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_3.lab37 \
        -in $site_5_3 -x 20 -y 10 -width 920 -relwidth 0 -height 315 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tNo40 \
        -in $site_3_0 -x 20 -y 10 -width 1405 -relwidth 0 -height 800 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure TSizegrip -background #d9d9d9
    vTcl::widgets::ttk::sizegrip::CreateCmd $top.tSi46 \
        -cursor size_nw_se 
    vTcl:DefineAlias "$top.tSi46" "TSizegrip1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab39 \
        -activebackground {#ffffff} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Interference Recognition} 
    vTcl:DefineAlias "$top.lab39" "LabelDemoTitle" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab37 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black \
        -image [vTcl:image:get_image [file join D:/ ownCloud wishful-framework-cnit wishful-github-manifest-7 final_showcase showcase_GUI cnit_GUI logo_wishful.png]] \
        -text Label 
    vTcl:DefineAlias "$top.lab37" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab38 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black \
        -image [vTcl:image:get_image [file join D:/ ownCloud wishful-framework-cnit wishful-github-manifest-7 final_showcase showcase_GUI cnit_GUI logo_cnit2.png]] \
        -text Label 
    vTcl:DefineAlias "$top.lab38" "Label2" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tFr39 \
        -in $top -x 7 -y 103 -width 1435 -relwidth 0 -height 830 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tSi46 \
        -in $top -x 1160 -relx 1 -y 860 -rely 1 -anchor se -bordermode inside 
    place $top.lab39 \
        -in $top -x 520 -y 40 -width 434 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab37 \
        -in $top -x 90 -y -10 -width 386 -relwidth 0 -height 109 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab38 \
        -in $top -x 940 -y 0 -width 392 -relwidth 0 -height 82 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top34

