## WiSHFUL Controller's config file

parameters:
  controllerName: "WIFI_TUB_1"
  ssid: "Ph0-WiFi-1"
  hostapd_config: "ap1_hostapd.conf"
  wpa_supplicant_config: "sta1_wpa_supplicant.conf"
  ap0_iface: "wlp2s0"
  sta0_iface: "wlp2s0"

controller:
    name: "OBSS_Management_Solution"
    info: "Overlaping BSS Management WiSHFUL Controller"
    dl: "tcp://10.0.0.20:8990"
    ul: "tcp://10.0.0.20:8989"

modules:
    discovery:
        module : wishful_module_discovery_pyre
        class_name : PyreDiscoveryControllerModule
        kwargs: {"iface":"eno1", "groupName":"wifi_warmup_wifi_1", "downlink":"tcp://10.0.0.20:8990", "uplink":"tcp://10.0.0.20:8989"}
